---
title: "NEW _ covid"
author: "Jinwoo Lee"
date: "4/22/2022"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(topicmodels)
library(rtweet)
library(dplyr)
library(tidytext)
library(stringr)
library(tidyr)
library(textdata)
library(topicmodels)
library(tm)
```

## Scrapping the data


```{r scraping}

# For example using covid instead of coronavirus

rt_other <- search_tweets(
  q="covid", n = 10000, type = "recent", include_rts = FALSE
)
rt_other<-rt_other%>%select("text", "favorite_count")
rt_other%>%arrange(desc(favorite_count))%>%head()
rt2_other<-rt_other%>%filter(favorite_count>10)
rt2_other
```

## Top 10 words
```{r topwords0}

tidy_rt_other <- rt_other %>% 
  unnest_tokens(word, text) %>% 
  mutate(word = str_extract(word, "[a-z]+")) %>%
  filter(!(word=="NA"))%>%
  anti_join(stop_words)

tidy_rt_other %>% 
  count(word, sort = TRUE)%>%head(10)



```

```{r topwords1}
custom_stop_words <- bind_rows(stop_words,
                               data_frame(word = union(tm::stopwords("spanish"),tm::stopwords("french") ),
                                          lexicon = "custom"))
tidy_rt_other <- rt_other %>% 
  unnest_tokens(word, text) %>% 
  mutate(word = str_extract(word, "[a-z]+")) %>%
  filter(!(word=="NA"))%>%
  filter(!(word=="da"))%>%
  anti_join(custom_stop_words)

tidy_rt_other %>% 
  count(word, sort = TRUE)%>%head(10)



```


```{r topwords2}
tidy_rt2_other <- rt2_other %>% 
  unnest_tokens(word, text) %>% 
  mutate(word = str_extract(word, "[a-z]+")) %>%
  filter(!(word=="NA"))%>%
  filter(!(word=="da"))%>%
  anti_join(custom_stop_words)

tidy_rt2_other %>% 
  count(word, sort = TRUE)%>%head(10)



```

## Top 10 bigrams


```{r topbigrams1}
tidy_rt_bigram_other <- rt_other %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2)%>% 
filter(bigram != "NA")
tidy_rt_bigram_other %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  mutate(word1 = str_extract(word1, "[a-z]+")) %>%
  mutate(word2 = str_extract(word2, "[a-z]+")) %>%
  filter(!word1 %in% custom_stop_words$word) %>% 
  filter(!word2 %in% custom_stop_words$word)%>% 
  filter(!(word1=="NA"|word2=="NA"))%>%
  unite(bigram, word1, word2, sep=" ")%>% 
  count(bigram, sort = TRUE)%>%head(30)
```


```{r topbigrams2}

tidy_rt2_bigram_other <- rt2_other %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2)%>% 
filter(bigram != "NA")
tidy_rt2_bigram_other %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  mutate(word1 = str_extract(word1, "[a-z]+")) %>%
  mutate(word2 = str_extract(word2, "[a-z]+")) %>%
  filter(!word1 %in% custom_stop_words$word) %>% 
  filter(!word2 %in% custom_stop_words$word)%>% 
  filter(!(word1=="NA"|word2=="NA"))%>%
  filter(!(word1=="da"|word2=="da"))%>%
  unite(bigram, word1, word2, sep=" ")%>% 
  count(bigram, sort = TRUE)%>%head(30)
```


## nrc sentiment


```{r nrcsenti}
nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")
nrc_sad <- get_sentiments("nrc") %>% 
  filter(sentiment == "sadness")
nrc_anger <- get_sentiments("nrc") %>% 
  filter(sentiment == "anger")
nrc_fear <- get_sentiments("nrc") %>% 
  filter(sentiment == "fear")
nrc_trust <- get_sentiments("nrc") %>% 
  filter(sentiment == "trust")



tidy_rt_other %>%
  inner_join(nrc_joy) %>% 
  count(word, sort = TRUE)
tidy_rt_other %>%
  inner_join(nrc_sad) %>% 
  count(word, sort = TRUE)
tidy_rt_other%>%
  inner_join(nrc_anger) %>% 
  count(word, sort = TRUE)
tidy_rt_other %>%
  inner_join(nrc_fear) %>% 
  count(word, sort = TRUE)
tidy_rt_other %>%
  inner_join(nrc_trust) %>% 
  count(word, sort = TRUE)
```


## Plotting sentiment against favorite_count


```{r sentigraphs}
get_sentiment_total<-function(positive, negative){
  ret<-c()
  for(num in 1:length(positive)){
    pos<-positive[num]
    neg<-negative[num]
    if(is.na(pos) && is.na(neg)){
      ret<-append(ret, 0)
    }
    else if(is.na(pos)){
      ret<-append(ret, -1*neg)
    }
    else if (is.na(neg)){
      ret<-append(ret, pos)
    }
    else{
      ret<-append(ret, pos-neg)
    }
  }
  return(ret)
}
sentiment <- tidy_rt_other %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(favorite_count, sentiment) %>%
  pivot_wider(names_from = "sentiment", values_from = "n") %>% 
  mutate(sentiment = get_sentiment_total(positive, negative))
ggplot(sentiment, aes(favorite_count, sentiment, fill = sentiment)) + 
  geom_point() 

sentiment <- tidy_rt2_other %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(favorite_count, sentiment) %>%
  pivot_wider(names_from = "sentiment", values_from = "n") %>% 
  mutate(sentiment = get_sentiment_total(positive, negative))
ggplot(sentiment, aes(favorite_count, sentiment, fill = sentiment)) + 
  geom_point() 

```